### Get all
GET http://localhost:3000/empleados/ HTTP/1.1

### Get by id
GET http://localhost:3000/empleados/5f6f88c44786ab280896ecf1 HTTP/1.1

### Get by user
GET http://localhost:3000/empleados/username/mima HTTP/1.1

### Update pass
PUT http://localhost:3000/empleados/pass/5f725f6f35fa984230f8d7f3 HTTP/1.1
content-type: application/json

{
    "pass": "12345",
    "newPass": "1234",
    "confirm": "1234"
}

### Update user
PUT http://localhost:3000/empleados/empleado/5f7634754df9d3242c7fec18 HTTP/1.1
content-type: application/json

{
    "username": "asdffffff",
    "email": "hfjsdjgfsj"
}